routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

//Resource Routes
Route::resource('flight', 'FlightController');

//Other Routes
Route::get('sendMail', 'MailController@sendMail');
//Page route
Route::get('/', 'HomeController@index')->name('home');

app/Agency.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Agency extends Model
{
    protected $table = 'agency';
}

app/Flight.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Flight extends Model
{
    protected $table = 'flights';
}

app/ReferralSrc.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ReferralSrc extends Model
{
    protected $table = 'referral_src';
}

app/Traveller.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Traveller extends Model
{
    protected $table = 'travellers';
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/FlightAPIController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class FlightAPIController extends Controller
{
    public function getAirports(){
        
    }
}

app/Http/Controllers/FlightController.php
<?php

namespace App\Http\Controllers;

use Exception;
use App\Agency;
use App\Flight;
use App\Traveller;
use App\ReferralSrc;
use Illuminate\Http\Request;

class FlightController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $ref = ReferralSrc::all();
        $agency = Agency::first();
        return view('flight.add', [
            'ref' => $ref,
            'agency' => $agency
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try{
            $flight = new Flight();
            $flight->email = $request->input('email');
            $flight->phone = $request->input('phone');
            $flight->travel_from_date = $request->input('travel_from_date');
            $flight->travel_to_date = $request->input('travel_to_date');
            $flight->travel_from_loc = $request->input('travel_from_loc');
            $flight->travel_to_loc = $request->input('travel_to_loc');
            $flight->other_flight_details = $request->input('other_flight_details');
            $flight->visa_interview_date = $request->input('visa_interview_date');
            $flight->visa_consulate = $request->input('visa_consulate');
            $flight->referral_src_code = $request->input('referral_src_code');
            $flight->is_traveler = ($request->input('is_traveler') == 1 ? true : false);
            $flight->flight_price = $request->input('flight_price');
            $flight->total_payment = $request->input('total_payment');
            $flight->save();

            $fname = $request->get('fname');
            $lname = $request->get('lname');
            echo count($fname);
            for($i = 1; $i <= count($fname); $i++){
                $trav = new Traveller();
                $trav->flight_id = $flight->id;
                $trav->first_name = $fname[$i];
                $trav->last_name = $lname[$i];
                $trav->save();
            }

            $notification = array(
                'message' => 'Flight successfully added',
                'alert-type' => 'success'
            );
            return redirect()->back()->with($notification);
        } 
        catch(Exception $e){
            
        }
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index()
    {
        return view('pages.home');
    }
}

app/Http/Controllers/MailController.php
<?php

namespace App\Http\Controllers;

use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

class MailController extends Controller
{
    public function sendMail(Request $request){
        $subject = 'Test subject';
        try{
            Mail::send('template.itinerary', $arr, function ($message) use ($subject){
                $msg->subject($subject);
            });

            if (Mail::failures()) {
                echo 'wala naabot';
            }
        }
        catch(Exception $e){

        }
    }
}

resources/views/flight/add.blade.php
@extends('layouts.app')

@section('content')
<section id="fh5co-home" data-section="home" class="formHeader"  data-stellar-background-ratio="0.5">
    <div class="gradient"></div>
    <div class="container">
        <div class="text-wrap headerText">
            <div class="text-inner valign-bottom">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2 text-center">
                        <h1 class="to-animate">Fill details - Pay - get Itinerary via Email</h1>
                        <h2 class="to-animate">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec varius turpis ut varius dignissim. Suspendisse quis venenatis risus, sit amet auctor ex. Morbi congue finibus nibh sit amet dapibus. Sed dignissim enim venenatis nisl porta dictum.</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section id="fh5co-services" data-section="services">
    <div class="fh5co-services">
        <div class="container">
            <div class="row">
                <div class="col-md-12 section-heading mysection-heading text-center">
                    <h2 class="to-animate"><span>Flight reservation form(24 hours delivery)</span></h2>
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2 subtext">
                            <h3 class="to-animate">Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
                                    Suspendisse nec mi pellentesque,condimentum leo id, gravida felis.  </h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<form class="formContainer">    
    <div class="container">
        <form action="{{ route('flight.store') }}" method="POST">
        {{ csrf_field() }}
            <div class="row divTravellerContainer">
                <h4>Traveler Details</h4>
                <div class="form-group col-md-6">
                    <small>Email *</small>
                    <input type="email" name="email" class="form-control" required />
                </div>
                <div class="form-group col-md-6">
                    <small>Phone *</small>
                    <input type="tel" name="phone" class="form-control" required />
                </div>
                <h4>Guest Info</h4>
                <div class="col-md-12 divTraveller trav-template">
                    <div class="form-group col-md-6">
                        <input type="text" class="form-control fname" placeholder="Enter first name" />
                    </div>
                    <div class="form-group col-md-5">
                        <input type="text" class="form-control lname" placeholder="Enter last name" />
                    </div>
                    <div class="form-group col-md-1 btnDiv">
                        <a href="" class="btn btn-primary btnTraveller"><i class="fa fa-plus"></i> Add</a>
                    </div>
                </div>
            </div>
            <div class="row divFlightContainer">
                <h4>Flight Details</h4>
                <div class="form-group col-md-6">
                    <small>Departing on *</small>
                    <input type="date" name="travel_from_date" class="form-control" required />
                </div>
                <div class="form-group col-md-6">
                    <small>From/To (City/Airport) *</small>
                    <input type="text" id="txtFromLoc" name="travel_from_loc" class="form-control" required/>
                </div>
                <div class="form-group col-md-6">
                    <small>Returning on</small>
                    <input type="date" name="travel_to_date" class="form-control" />
                </div>
                <div class="form-group col-md-6">
                    <small>From/To (City/Airport)</small>
                    <input type="text" name="travel_to_loc" class="form-control" />
                </div>
                <div class="form-group col-md-12">
                    <small>Other details</small>
                    <textarea class="form-control" name="other_flight_details"></textarea>
                </div>
                <h4>General Information</h4>
                <div class="form-group col-md-4">
                    <small>Visa interview date</small>
                    <input type="date" name="visa_interview_date" class="form-control" />
                </div>
                <div class="form-group col-md-4">
                    <small>Consulate</small>
                    <input type="text" name="visa_consulate" class="form-control" />
                </div>
                <div class="form-group col-md-4">
                    <small>How did you hear about us?</small>
                    <select name="referral_src_code" class="form-control">
                        @foreach($ref as $r)
                            <option value="{{ $r->referral_src_code }}">{{ $r->description }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group col-md-12">
                    <label>Are you one of the travellers making the payment? *</label>
                    <input type="radio" name="is_traveller" value="1" /> Yes 
                    <input type="radio" name="is_traveller" value="0" /> No
                </div>
            </div>
            <div class="row divOrderContainer">
                <h4>Order Summary</h4>
                <div class="form-group col-md-12">
                    <small>Flight Itinerary</small> 
                    <input type="text" id="txtFlightPrice" name="flight_price" value="0" readonly />
                </div>
                <div class="form-group col-md-12">
                    <small>Total payment</small> 
                    <input type="text" id="txtTotalPayment" name="total_payment" value="0" readonly />
                </div>
            </div>
            <button class="primary">PAY NOW</button>
        </form>
    </div>
</form>

@endsection

@push('scripts')
<script type="text/javascript">
    $(document).ready(function(){
        var initHandlers = function(){
            $('.btnTraveller').on('click',function(e){
                e.preventDefault();
                var obj = $(this);
                
                if(obj.hasClass('btn-primary')){
                    var fname = obj.closest('.divTraveller').find('.fname');
                    var lname = obj.closest('.divTraveller').find('.lname');
                    if(fname.val() == "") fname.addClass('error');
                    if(lname.val() == "") lname.addClass('error');
                    
                    if(fname.val() != "" && lname.val() != ""){
                        var cnt = $('.traveller').length + 1;
                        var trav_temp = $('.trav-template').clone().removeClass('trav-template').addClass('traveller');
                        trav_temp.find('.btnDiv a').removeClass('btn-primary').addClass('btn-danger').click(function(){
                            $(this).closest('.divTraveller').remove();
                            calculatePrice();
                        });
                        trav_temp.find('.fname').attr('name','fname[' + cnt + ']').attr('required','required');
                        trav_temp.find('.lname').attr('name','lname[' + cnt + ']').attr('required','required');
                        trav_temp.find('.btnDiv a').html('<i class="fa fa-minus"></i> Remove');
                        trav_temp.appendTo('.divTravellerContainer');
                        fname.val('');
                        lname.val('');
                    }
                }
            });

            $(".btnTraveller").on("click", function(){
                calculatePrice();
            });

            $(".fname,.lname").on('keyup', function(){
                var obj = $(this);
                if(obj.val() == '') obj.addClass('error');
                else obj.removeClass('error');
            });

            $( "#txtFromLoc" ).autocomplete({
                source: function( request, response ) {
                    $.ajax({
                        url: "https://api.sandbox.amadeus.com/v1.2/airports/autocomplete",
                        dataType: "json",
                        type: 'GET',
                        data: {
                            apikey: "sd4yRuYt7y2Yl2mWi0vcG85nksj2pcvB",
                            term: request.term
                        },
                        success: function( data ) {
                            response( data );
                        }
                    });
                },
                minLength: 3,
                select: function( event, ui ) {
                    log( ui.item ?
                        "Selected: " + ui.item.label :
                        "Nothing selected, input was " + this.value);
                },
                open: function() {
                    $( this ).removeClass( "ui-corner-all" ).addClass( "ui-corner-top" );
                },
                close: function() {
                    $( this ).removeClass( "ui-corner-top" ).addClass( "ui-corner-all" );
                }
            });
        };

        var calculatePrice = function(){
            var cnt = $('.traveller').length;
            var price = {!! $agency->price_6h !!} * cnt;
            $("#txtFlightPrice,#txtTotalPayment").val(price);
        };

        var build = function(){
            initHandlers();
        };
        build();
    });
</script>
@endpush

resources/views/inc/navbar.blade.php
<header role="banner" id="fh5co-header">
    <div class="fluid-container">
        <nav class="navbar navbar-default">
            <div class="navbar-header">
                <!-- Mobile Toggle Menu Button -->
                <a href="#" class="js-fh5co-nav-toggle fh5co-nav-toggle" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"><i></i></a>
                <a  href="{{ route('home') }}"><img class="logo" src="{{ URL::to('/') }}/img/logo.png" alt="reserva"></a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right navbottom">
                    <li class="active"><a href="{{ route('home') }}" data-nav-section="home"><span>HOME</span></a></li>
                    <li><a href="#" data-nav-section="pricing"><span>PRICING</span></a></li>
                    <li><a href="#" data-nav-section="services"><span>SERVICES</span></a></li>
                    <li><a href="#" data-nav-section="faq"><span>FAQ</span></a></li>
                    <li class="call-to-action"><a class="log-in" href="#"><span>CONTACT US</span></a></li>
                </ul>
            </div>
        </nav>
    </div>
</header>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css" />
    <!-- Style -->
    <link rel="stylesheet" href="{{ asset('css/helper/style.css')}}">
    <!-- Animate.css -->
    <link rel="stylesheet" href="{{ asset('css/helper/animate.css')}}">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="{{ asset('css/helper/icomoon.css')}}">
    <!-- Simple Line Icons -->
    <link rel="stylesheet" href="{{ asset('css/helper/simple-line-icons.css')}}">
    <!-- Owl Carousel  -->
    <link rel="stylesheet" href="{{ asset('css/helper/owl.carousel.min.css')}}">
    <!-- Custom CSS here-->
    <link rel="stylesheet" href="{{ asset('css/helper/owl.theme.default.min.css')}}">
    <!-- Style -->
    <link rel="stylesheet" href="{{ asset('css/helper/style.css')}}">


    <link href="{{ asset('css/app.css') }}" rel="stylesheet">  
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet">
    <link href="{{ asset('css/master.css') . '?v=1518846252668' }}" rel="stylesheet">
    
   
    <!-- Modernizr JS -->
    <script src="{{ asset('js/helper/modernizr-2.6.2.min.js')}}"></script>
    
    
</head>
<body>
    <div id="app">
        @include('inc.navbar')

        <div class="container-fluid">
            @yield('content')
        </div>
    </div>

    <!-- Scripts -->


  
    <script src="{{ asset('js/app.js') }}"></script> 
    {{--  <script src="{{ asset('js/helper/jquery.min.js')}}"></script>   --}}
    <script src="//code.jquery.com/jquery.js"></script> 
    <!-- jQuery -->
    
    <!-- jQuery Easing -->
    <script src="{{ asset('js/helper/jquery.easing.1.3.js')}}"></script>
     <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script> 
    <!-- Waypoints -->
    <script src="{{ asset('js/helper/jquery.waypoints.min.js')}}"></script>
    <!-- Stellar Parallax -->
    <script src="{{ asset('js/helper/jquery.stellar.min.js')}}"></script>
    <!-- Owl Carousel -->
    <script src="{{ asset('js/helper/owl.carousel.min.js')}}"></script>
    <!-- Counters -->
    <script src="{{ asset('js/helper/jquery.countTo.js')}}"></script>


    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>  
    <!-- Bootstrap -->
	{{--  <script src="{{ asset('js/helper/bootstrap.min.js')}}"></script>  --}}
    
    <!-- Custom scripts here-->
    <!-- Main JS (Do not remove) -->
    <script src="{{ asset('js/helper/main.js')}}"></script>
    <script type="text/javascript">
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
       
    </script>
    <script>
        @if(Session::has('message'))
            var type = "{{ Session::get('alert-type', 'info') }}";
            switch(type){
                case 'info':
                    toastr.info("{{ Session::get('message') }}");
                    break;

                case 'warning':
                    toastr.warning("{{ Session::get('message') }}");
                    break;

                case 'success':
                    toastr.success("{{ Session::get('message') }}");
                    break;

                case 'error':
                    toastr.error("{{ Session::get('message') }}");
                    break;
            }
        @endif
    </script>
    {!! Toastr::render() !!}
    @stack('scripts')
</body>
</html>

resources/views/pages/home.blade.php
@extends('layouts.app')

@section('content')
	<section class="homeImage" id="fh5co-home" data-section="home" style="background-image: url(img/homeImage1.jpg); background-repeat: no-repeat;"  data-stellar-background-ratio="0.5">
		<div class="gradient"></div>
			<div class="container">
				<div class="text-wrap headerText">
					<div class="text-inner valign-bottom">
						<div class="row">
							<div class="col-md-8 col-md-offset-2 bottom-align-text alignLeft">
								<h1 class="to-animate text-left">Applying</h1>
								<h1 class="to-animate text-left">for visa traveling?</h1>
								<h2 class="to-animate text-left">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec varius turpis ut varius dignissim. Suspendisse quis venenatis risus, sit amet auctor ex. Morbi congue finibus nibh sit amet dapibus. Sed dignissim enim venenatis nisl porta dictum.</h2>
								<div class="call-to-action">
									<a href="#" class="learnMore to-animate"><i class="icon-learnMore"></i> Learn More</a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
	</section>
	<section id="fh5co-services" data-section="services">
		<div class="fh5co-services">
			<div class="container">
				<div class="row">
					<div class="col-md-12 section-heading text-center">
						<h2 class="to-animate"><span>Three easy steps</span></h2>
						<div class="row">
							<div class="col-md-8 col-md-offset-2 subtext">
								<h3 class="to-animate">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sit amet convallis mi, eleifend sodales dolor. Curabitur sed magna quis massa pellentesque pulvinar vel vel nibh. Fusce in libero id dui commodo bibendum. </h3>
							</div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-4 text-center">
						<div class="box-services">
							<div class="icon to-animate">
								<img class="logo" src="img/step1.png" alt="step1">
							</div>
							<div class="fh5co-post to-animate">
								<h3>Select Plan</h3>
								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sit amet convallis mi, eleifend sodales dolor. Curabitur sed magna quis massa pellentesque pulvinar vel vel nibh.</p>
							</div>
						</div>
					</div>
					<div class="col-md-4 text-center">
						<div class="box-services">
							<div class="icon to-animate">
								<img class="logo" src="img/step2.png" alt="step1">
							</div>
							<div class="fh5co-post to-animate">
								<h3>Submit Travel Details and Pay</h3>
								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sit amet convallis mi, eleifend sodales dolor. Curabitur sed magna quis massa pellentesque pulvinar vel vel nibh.</p>
							</div>
						</div>
					</div>
					<div class="col-md-4 text-center">
						<div class="box-services">
							<div class="icon to-animate">
								<img class="logo" src="img/step3.png" alt="step1">
							</div>
							<div class="fh5co-post to-animate">
								<h3>Receive Itinerary in Email</h3>
								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sit amet convallis mi, eleifend sodales dolor. Curabitur sed magna quis massa pellentesque pulvinar vel vel nibh.</p>
							</div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-offset-3 col-md-2 hidden-sm hidden-xs text-center">
						<div class="box-services">
							<div class="icon to-animate">
								<img class="logo" src="img/arrow1.png" alt="step1">
							</div>
						</div>
					</div>
					<div class="col-md-offset-2 col-md-2 hidden-sm hidden-xs text-center">
						<div class="box-services">
							<div class="icon to-animate">
								<img class="logo" src="img/arrow1.png" alt="step1">
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<section id="fh5co-pricing" data-section="pricing" style="background-image: url(img/pricingImg.jpg); background-repeat: round;" >
		<div class="fh5co-pricing">
			<div class="container-fluid">
				<div class="row">
					<div class="col-md-12 section-heading text-right headerPadding">
						<h2 class="to-animate"><span>Flight reservation pricing</span></h2>
					</div>
				</div>	
				<div class="row">
					<div class="clearfix visible-sm-block"></div> 
					<div class="col-md-offset-6 col-md-3 col-sm-6 to-animate">
						<div class="price-box to-animate">
							<h2 class="pricing-plan">Regular</h2>
							<div class="price"><sup class="currency">$</sup>15<small>per traveler</small></div>
							<p>24 hour email delivery</p>
							<hr>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sit amet convallis mi, eleifend sodales dolor.</p>
							<p><a href="{{ route('flight.create') }}" class="btn btn-primary">ORDER NOW</a></p>
						</div>
					</div>
					<div class="col-md-3 col-sm-6">
						<div class="price-box to-animate">
							<h2 class="pricing-plan">Enterprise</h2>
							<div class="price"><sup class="currency">$</sup>25<small>per traveler</small></div>
							<p>6 hour email delivery</p>
							<hr>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sit amet convallis mi, eleifend sodales dolor.</p>
							<p><a href="{{ route('flight.create') }}" class="btn btn-primary">ORDER NOW</a></p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<div class="container-fluid contactContainer">
		<div class="col-md-offset-2 col-md-8">
			<form class="formContactUS">
				<div class="form-group row">
					<div class="col-lg-6">
						<input type="text" class="form-control fname" placeholder="Enter email" />
					</div>
					<div class="col-lg-6">
						<input type="text" class="form-control lname" placeholder="Enter fullname" />
					</div>
				</div>
				<div class="form-group row">
					<div class="col-lg-12">
						<textarea name="message" id="message" class="form-control" rows="4" placeholder="Message" required></textarea>
					</div>
				</div>
				<div class="form-group row">
					<div class="col-lg-4">
					</div>
					<div class="col-lg-8"> 
						<button class="btn btn-primary" id="btnSubmit">Submit</button>
					</div>
				</div>
			</form>
		</div>  
	</div>
@endsection

@push('scripts')

@endpush

resources/views/template/itinerary.blade.php
Sample